package com.example.stockapp

import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

// Retrofit client for OpenRouter
object OpenRouterClient {
    private const val BASE_URL = "https://openrouter.ai/"

    val api: OpenRouterApi by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(OpenRouterApi::class.java)
    }

    suspend fun getAiAnalysis(prompt: String): String {
        val authHeader = "Bearer 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"

        val requestBody = createJsonPayload(prompt)

        // Call the Retrofit interface asynchronously using Kotlin suspend mechanics
        val response = api.getCompletion(authHeader, requestBody)

        return response.choices.firstOrNull()?.message?.content ?: "No analysis generated by the market models."
    }

    private fun createJsonPayload(prompt: String): okhttp3.RequestBody {
        val json = JSONObject().apply {
            put("model", "deepseek/deepseek-v4-flash:free") // Declares the free Tier model
            put("messages", JSONArray().put(JSONObject().apply {
                put("role", "user")
                put("content", prompt)
            }))
        }
        return json.toString().toRequestBody("application/json".toMediaType())
    }
}