package com.example.stockapp

import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

// Retrofit client for OpenRouter
object OpenRouterClient {
    private const val BASE_URL = "https://openrouter.ai/"

    val api: OpenRouterApi by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(OpenRouterApi::class.java)
    }

    /**
     * Executes an asynchronous cloud GenAI query as taught in Module 4 & 9 slides.
     * Takes a single prompt string and returns the assistant's structured commentary response text.
     */
    suspend fun getAiAnalysis(prompt: String): String {
        // Build the authorization headers securely following cloud integration patterns
        val authHeader = ""

        // Wrap your JSON structural mapping using structured request payloads safely
        val requestBody = createJsonPayload(prompt)

        // Call the Retrofit interface asynchronously using Kotlin suspend mechanics
        val response = api.getCompletion(authHeader, requestBody)

        // Extract out the message content string from the choice model layers safely
        return response.choices.firstOrNull()?.message?.content ?: "No analysis generated by the market models."
    }

    /**
     * Helper to construct valid OpenRouter JSON structures without manual string manipulation bugs
     */
    private fun createJsonPayload(prompt: String): okhttp3.RequestBody {
        val json = JSONObject().apply {
            put("model", "google/gemma-2-9b-it:free") // Declares the free Tier model
            put("messages", JSONArray().put(JSONObject().apply {
                put("role", "user")
                put("content", prompt)
            }))
        }
        return json.toString().toRequestBody("application/json".toMediaType())
    }
}